

const LoginRegisterlang = {
    en: {
      platformWelcome: 'Welcome to the educational platform',
      continueWatching: 'Continue watching the courses you have already started',
      lastName: 'Last Name',
      firstName: 'First Name',
      accountType: 'Account Type',
      birthYear: 'Date of Birth',
      mobileNo: 'Phone Number',
      studentId: 'Student ID',
      password: 'Password',
      email: 'Email Address',
      otp: 'Verification Code',
      verify: 'Verify',
      resend: 'Resend',
      register: 'Register',
      loginPrompt: 'Already have an account? Log in now',
      internalStudent: 'Internal Student',
      externalStudent: 'External Student',
      public: 'Public',
      instructor: 'Instructor',
      placeholderEmail: 'email@example.com',
      placeholderPhone: 'Phone Number',
      placeholderPassword: '********',
    },
    ar: {
      platformWelcome: 'مرحبًا بك في المنصة التعليمية',
      continueWatching: 'استمر في مشاهدة الدورات التدريبية التي بدأت مشاهدتها بالفعل',
      lastName: 'اللقب',
      firstName: 'الاسم',
      accountType: 'نوع الحساب',
      birthYear: 'تاريخ الميلاد',
      mobileNo: 'رقم الهاتف',
      studentId: 'رقم القيد',
      password: 'كلمة المرور',
      email: 'عنوان البريد الإلكتروني',
      otp: 'رمز التحقق',
      verify: 'تحقق',
      resend: 'إعادة إرسال',
      register: 'تسجيل',
      loginPrompt: 'لديك حساب؟ قم بتسجيل الدخول الآن',
      internalStudent: 'طالب داخلي',
      externalStudent: 'طالب خارجي',
      public: 'عام',
      instructor: 'مدرب',
      placeholderEmail: 'email@example.com',
      placeholderPhone: 'رقم الهاتف',
      placeholderPassword: '********',
    },
  };
  export default LoginRegisterlang