export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as LoginRegister } from "./LoginRegister";
export { default as HomeAfterLogin } from "./HomeAfterLogin";
export { default as NavbarLogin } from "../component/NavbarLogin";
export { default as ContinueReadingSection } from "../component/ContinueReadingSection";
export { default as MyCourses } from "./MyCourses";
export { default as MyBooks } from "./MyBooks";
export { default as Shop } from "./Shop";
export { default as ReadBooks } from "./ReadBooks";
export { default as BookDetails } from "./BookDetails";
export { default as CoursesDetails } from "./CoursesDetails";
export { default as Showcourse } from "./Showcourse";
export { default as ShoppingCart } from "../component/ShoppingCart";
export { default as Settings } from "./Settings";
export { default as Profile } from "./Profile";
export { default as OrderHistory } from "./OrderHistory";
export { default as AllNotify } from "./AllNotify";
export { default as BorrowsHistory } from "./BorrowsHistory";
export { default as Myborrow } from "./Myborrow";
export { default as OrderConfirmation } from "./OrderConfirmation";
export { default as Seminars } from "./Seminars";
export { default as Contests } from "./Contests";
export { default as SeminarsDetails } from "./SeminarsDetails";
export { default as CompetitionsDetails } from "./CompetitionsDetails";
export { default as MyActivity } from "./MyActivity";
export { default as Allactivity } from "./Allactivity";
export { default as ContestsDetails } from "./ContestsDetails";
export { default as TrainingCoursesDtails } from "./TrainingCoursesDtails";
export { default as Paytheorder } from "./Paytheorder";


export {};
